name: CI

on:
  pull_request:
    branches:
    - redesing-navigation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ESLint Action
      uses: hallee/eslint-action@1.0.1
